"""Runtime support for simulated dynamics in generated IOCs and TANGO devices.

Generated IOC classes derive from `CASimulatedPVGroup` or `PVASimulatedPVGroup`,
and generated TANGO device classes from `TangoSimulatedDevice`. All three drive
two kinds of behaviour defined in the device definitions:

* setpoint/readback pairs (`PVPair`), where the readback follows its setpoint
  through a response model rather than instantly;
* update signals, where a PV's value is generated by a signal function.

Both are per-device, so they are supplied when the IOC is constructed rather
than baked into the generated class, which is shared by all devices of a type.
"""

from abc import ABC, abstractmethod

from caproto.server import PVGroup
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional
import threading
import warnings
import time
from ..effects.resolve import call_signal

DEFAULT_TIMESTEP = 0.1
"""Timestep used when the IOC runner does not specify one, in seconds."""


def _values_equal(a, b) -> bool:
    """Whether a readback already holds a value, avoiding a needless CA update.

    Waveform PVs compare element-wise, which is ambiguous as a truth value; such
    values are treated as changed and written.
    """
    try:
        return bool(a == b)
    except (TypeError, ValueError):
        return False


@dataclass
class PVPair:
    """A setpoint and the readback that follows it.

    `setpoint` and `readback` are the PV handles as defined in the device YAML,
    i.e. the attribute names on the generated IOC class. `dynamics` is the
    response model relating the two, called as ``dynamics(target, dt)``; with no
    response model the readback tracks its setpoint immediately.
    """

    setpoint: str
    readback: str
    dynamics: Callable | None = None

    def __call__(self, target, dt):
        if self.dynamics is None:
            return target
        return self.dynamics(target, dt)


@dataclass
class UpdateSignal:
    """A PV whose value is generated by a signal function."""

    handle: str
    signal: Callable


class SimulationPVBase:
    """A `PVGroup` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        if timestep <= 0:
            raise ValueError(f"timestep must be positive, got {timestep}")
        self.timestep = timestep
        self.pv_pairs = list(pv_pairs) if pv_pairs else []
        self.updates = list(updates) if updates else []
        self.elapsed = 0.0
        self._driving = False
        self._missing = set()

    def _channel(self, handle: str):
        """The channel for a PV handle, or None if this device does not have it.

        Devices of the same type do not all define the same PVs, so a pair or
        update naming an absent one is skipped rather than being an error. It is
        reported once, not on every tick.
        """
        channel = getattr(self, handle, None)
        if channel is None and handle not in self._missing:
            self._missing.add(handle)
            warnings.warn(
                f"{type(self).__name__} has no PV '{handle}'; not simulating it."
            )
        return channel


class PVASimulatedPVGroup(SimulationPVBase):
    """A `SimulationPVBase` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        super().__init__(
            timestep=timestep,
            pv_pairs=pv_pairs,
            updates=updates,
            *args,
            **kwargs,
        )


    def drive(self) -> None:
        """Advance the simulation forever, one `timestep` at a time.

        Every PV in a generated IOC calls this on startup, but only the first
        such call drives the group; the rest return immediately. Which PVs a
        given device exposes is not known when the class is generated, so this
        is the only way to guarantee the loop starts.
        """
        if self._driving or not (self.pv_pairs or self.updates):
            return
        self._driving = True
        while True:
            self.tick()
            time.sleep(self.timestep)

    def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        A PV can be driven by both a pair and an update signal -- a readback that
        lags its setpoint and is also noisy -- so the contributions are composed
        into one value and written once. Writing each separately would put both
        the clean and the noisy value on the wire, and a client monitoring the PV
        would see them alternate.
        """
        values = {}

        for pair in self.pv_pairs:
            setpoint = self._channel(pair.setpoint)
            readback = self._channel(pair.readback)
            if setpoint is None or readback is None:
                continue
            values[pair.readback] = (readback, pair(setpoint.current(), self.timestep))

        for update in self.updates:
            channel = self._channel(update.handle)
            if channel is None:
                continue
            # Start from this tick's value where a pair has already produced one,
            # so that noise is applied to the value the readback is moving to.
            _, current = values.get(update.handle, (None, channel.current()))
            values[update.handle] = (
                channel,
                call_signal(
                    update.signal,
                    t=self.elapsed,
                    value=current,
                    dt=self.timestep,
                ),
            )

        for channel, value in values.values():
            if not _values_equal(
                value[0] if isinstance(value, tuple) else value, channel.current()
            ):
                raw = channel.current().raw
                raw["value"] = value[0] if isinstance(value, tuple) else value
                channel.post(raw)

        self.elapsed += self.timestep


class CASimulatedPVGroup(PVGroup, SimulationPVBase):
    """A `PVGroup` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        SimulationPVBase.__init__(
            self,
            timestep=timestep,
            pv_pairs=pv_pairs,
            updates=updates,
            *args,
            **kwargs,
        )
        PVGroup.__init__(self, *args, **kwargs)

    async def drive(self, async_lib) -> None:
        """Advance the simulation forever, one `timestep` at a time.

        Every PV in a generated IOC calls this on startup, but only the first
        such call drives the group; the rest return immediately. Which PVs a
        given device exposes is not known when the class is generated, so this
        is the only way to guarantee the loop starts.
        """
        if self._driving or not (self.pv_pairs or self.updates):
            return
        self._driving = True
        while True:
            await self.tick()
            await async_lib.library.sleep(self.timestep)

    async def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        A PV can be driven by both a pair and an update signal -- a readback that
        lags its setpoint and is also noisy -- so the contributions are composed
        into one value and written once. Writing each separately would put both
        the clean and the noisy value on the wire, and a client monitoring the PV
        would see them alternate.
        """
        values = {}

        for pair in self.pv_pairs:
            setpoint = self._channel(pair.setpoint)
            readback = self._channel(pair.readback)
            if setpoint is None or readback is None:
                continue
            values[pair.readback] = (readback, pair(setpoint.value, self.timestep))

        for update in self.updates:
            channel = self._channel(update.handle)
            if channel is None:
                continue
            # Start from this tick's value where a pair has already produced one,
            # so that noise is applied to the value the readback is moving to.
            _, current = values.get(update.handle, (None, channel.value))
            values[update.handle] = (
                channel,
                call_signal(
                    update.signal,
                    t=self.elapsed,
                    value=current,
                    dt=self.timestep,
                ),
            )

        for channel, value in values.values():
            if not _values_equal(value, channel.value):
                await channel.write(value)

        self.elapsed += self.timestep


# --------------------------------------------------------------------------
# TANGO
# --------------------------------------------------------------------------


def _import_tango():
    """Import pytango on demand, so EPICS-only installs need not have it."""
    try:
        import tango
        from tango import AttrWriteType, DevState
        from tango.server import Device, attribute
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise ImportError(
            "pytango is required to serve TANGO devices: pip install pytango"
        ) from exc
    return tango, AttrWriteType, DevState, Device, attribute


@dataclass
class TangoAttribute:
    """Declaration of one attribute of a generated TANGO device class.

    Generated classes declare one of these per variable handle, in the way a
    caproto class declares a `pvproperty`. TANGO attributes belong to the
    device instance rather than the class, so the declaration is data, and
    `TangoSimulatedDevice.initialize_dynamic_attributes` creates the attribute
    on each device that defines the handle. `name` is the attribute's name on
    the network; `optional` marks handles that not every device of the type
    defines.
    """

    name: str
    dtype: Any
    initial: Any = 0.0
    access: Any = None
    unit: Optional[str] = None
    doc: Optional[str] = None
    enum_labels: Optional[List[str]] = None
    max_dim_x: Optional[int] = None
    optional: bool = False

    def attribute_kwargs(self) -> Dict[str, Any]:
        """Keyword arguments for `tango.server.attribute`."""
        _, AttrWriteType, _, _, _ = _import_tango()
        kwargs: Dict[str, Any] = {
            "name": self.name,
            "dtype": self.dtype,
            "access": self.access if self.access is not None else AttrWriteType.READ_WRITE,
        }
        if self.unit:
            kwargs["unit"] = str(self.unit)
        if self.doc:
            kwargs["doc"] = str(self.doc)
        if self.enum_labels:
            kwargs["enum_labels"] = list(self.enum_labels)
        if self.max_dim_x:
            kwargs["max_dim_x"] = int(self.max_dim_x)
        return kwargs

    @property
    def writable(self) -> bool:
        _, AttrWriteType, _, _, _ = _import_tango()
        access = self.access if self.access is not None else AttrWriteType.READ_WRITE
        return access in (AttrWriteType.READ_WRITE, AttrWriteType.WRITE, AttrWriteType.READ_WITH_WRITE)


@dataclass
class TangoDeviceSpec:
    """Per-device configuration of a `TangoSimulatedDevice`.

    TANGO creates device instances itself, from the names in the database, so
    the per-device information -- which handles the device defines, and its
    simulated behaviour -- cannot be passed to the constructor. It is
    registered beforehand with `TangoSimulatedDevice.configure` and looked up
    by device name in `init_device`.
    """

    handles: List[str]
    timestep: float = DEFAULT_TIMESTEP
    pv_pairs: List[PVPair] = field(default_factory=list)
    updates: List[UpdateSignal] = field(default_factory=list)
    initial_values: Dict[str, Any] = field(default_factory=dict)


def _tango_device_bases():
    """The bases of `TangoSimulatedDevice`, or plain bases if pytango is absent.

    Generated EPICS modules import this module too, and must not need pytango.
    """
    try:
        from tango.server import Device
    except ImportError:  # pragma: no cover - depends on the environment
        return (SimulationPVBase,)
    return (Device, SimulationPVBase)


class TangoSimulatedDevice(*_tango_device_bases()):
    """A TANGO `Device` that advances its simulated attributes on a fixed timestep.

    Subclasses declare their attributes as `TangoAttribute` class attributes,
    keyed by handle. Each device instance exposes only the handles its
    definition names, given by the `TangoDeviceSpec` registered for it with
    `configure` before the server starts; a device with no registered spec
    exposes every declared handle.

    Values are held per device in `_values`, keyed by handle, and served by
    the generic `_read_handle`/`_write_handle` methods. The simulation runs in
    a daemon thread per device and publishes each change as a TANGO change
    event, so clients may subscribe rather than poll.
    """

    _specs: Dict[str, TangoDeviceSpec] = {}

    # ---- class-level configuration -------------------------------------

    @classmethod
    def declared_attributes(cls) -> Dict[str, TangoAttribute]:
        """The `TangoAttribute` declarations of this class, keyed by handle."""
        declared: Dict[str, TangoAttribute] = {}
        for klass in reversed(cls.__mro__):
            for key, value in vars(klass).items():
                if isinstance(value, TangoAttribute):
                    declared[key] = value
        return declared

    @classmethod
    def configure(cls, device_name: str, spec: TangoDeviceSpec) -> None:
        """Register the per-device `spec` for `device_name` (case-insensitive)."""
        if "_specs" not in vars(cls):
            # Each generated class keeps its own registry rather than sharing
            # the base class's, so device types do not see each other's devices.
            cls._specs = {}
        cls._specs[device_name.lower()] = spec

    @classmethod
    def configured_devices(cls) -> List[str]:
        return list(vars(cls).get("_specs", {}).keys())

    # ---- TANGO lifecycle --------------------------------------------------

    def init_device(self):
        tango, _, DevState, Device, _ = _import_tango()
        Device.init_device(self)
        spec = vars(type(self)).get("_specs", {}).get(self.get_name().lower())
        self._spec = spec
        SimulationPVBase.__init__(
            self,
            timestep=spec.timestep if spec else DEFAULT_TIMESTEP,
            pv_pairs=spec.pv_pairs if spec else None,
            updates=spec.updates if spec else None,
        )
        self._values: Dict[str, Any] = {}
        self._attribute_names: Dict[str, str] = {}  # handle -> attribute name
        self._handles: Dict[str, str] = {}  # lower-case attribute name -> handle
        self._stop = threading.Event()
        self._thread = None
        self.set_state(DevState.ON)
        self.set_status("Simulated device")

    def initialize_dynamic_attributes(self):
        tango, _, _, _, attribute = _import_tango()
        declared = self.declared_attributes()
        handles = self._spec.handles if self._spec is not None else list(declared)
        for handle in handles:
            decl = declared.get(handle)
            if decl is None:
                warnings.warn(
                    f"{type(self).__name__} declares no attribute for handle "
                    f"'{handle}' of {self.get_name()}; not serving it."
                )
                continue
            initial = decl.initial
            if self._spec is not None and handle in self._spec.initial_values:
                initial = self._spec.initial_values[handle]
            self._values[handle] = initial
            self._attribute_names[handle] = decl.name
            self._handles[decl.name.lower()] = handle
            attr = attribute(
                fget=self._read_handle,
                fset=self._write_handle if decl.writable else None,
                **decl.attribute_kwargs(),
            )
            try:
                self.add_attribute(attr)
            except Exception as exc:
                # A failure here would otherwise take the whole server down,
                # EPICS IOCs included; serve the rest of the device instead.
                del self._values[handle]
                del self._attribute_names[handle]
                self._handles.pop(decl.name.lower(), None)
                warnings.warn(
                    f"Cannot add attribute '{decl.name}' to {self.get_name()}: "
                    f"{str(exc).splitlines()[0] if str(exc) else type(exc).__name__}"
                )
                continue
            # Events are pushed by the simulation, not detected by polling.
            self.set_change_event(decl.name, True, False)
        self.start()

    def delete_device(self):
        self.stop()

    # ---- attribute access -------------------------------------------------

    def _read_handle(self, attr):
        handle = self._handles[attr.get_name().lower()]
        attr.set_value(self._values[handle])

    def _write_handle(self, attr):
        handle = self._handles[attr.get_name().lower()]
        self._values[handle] = attr.get_write_value()

    def value(self, handle: str) -> Any:
        """The current value of `handle`."""
        return self._values[handle]

    def post(self, handle: str, value: Any) -> None:
        """Set `handle` to `value` and publish it as a change event."""
        self._values[handle] = value
        try:
            self.push_change_event(self._attribute_names[handle], value)
        except Exception as exc:  # pragma: no cover - depends on the value/type
            warnings.warn(f"Could not push change event for {self.get_name()}/{handle}: {exc}")

    # ---- simulation -------------------------------------------------------

    def _channel(self, handle: str):
        """The handle itself if this device serves it, else None (reported once)."""
        if handle in self._values:
            return handle
        if handle not in self._missing:
            self._missing.add(handle)
            warnings.warn(
                f"{type(self).__name__} {self.get_name()} has no attribute for "
                f"'{handle}'; not simulating it."
            )
        return None

    def start(self) -> None:
        """Start advancing the simulation, if there is anything to advance."""
        if self._driving or not (self.pv_pairs or self.updates):
            return
        self._driving = True
        self._thread = threading.Thread(
            target=self.drive, name=f"{self.get_name()} simulation", daemon=True
        )
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()

    def drive(self) -> None:
        """Advance the simulation until the device is deleted, one `timestep` at a time."""
        tango, _, _, _, _ = _import_tango()
        # Threads that call into TANGO must be registered with omniORB.
        with tango.EnsureOmniThread():
            while not self._stop.wait(self.timestep):
                try:
                    self.tick()
                except Exception as exc:  # pragma: no cover - keeps the device alive
                    warnings.warn(f"Simulation error in {self.get_name()}: {exc}")

    def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        As for the EPICS groups, a handle driven by both a pair and an update
        signal has the two composed into one value, which is written once.
        """
        values: Dict[str, Any] = {}

        for pair in self.pv_pairs:
            setpoint = self._channel(pair.setpoint)
            readback = self._channel(pair.readback)
            if setpoint is None or readback is None:
                continue
            values[readback] = pair(self._values[setpoint], self.timestep)

        for update in self.updates:
            handle = self._channel(update.handle)
            if handle is None:
                continue
            current = values.get(handle, self._values[handle])
            values[handle] = call_signal(
                update.signal,
                t=self.elapsed,
                value=current,
                dt=self.timestep,
            )

        for handle, value in values.items():
            if not _values_equal(value, self._values[handle]):
                self.post(handle, value)

        self.elapsed += self.timestep
