"""Runtime support for simulated dynamics in generated IOCs.

Generated IOC classes derive from `SimulatedPVGroup`, which drives two kinds of
behaviour defined in the device definitions:

* setpoint/readback pairs (`PVPair`), where the readback follows its setpoint
  through a response model rather than instantly;
* update signals, where a PV's value is generated by a signal function.

Both are per-device, so they are supplied when the IOC is constructed rather
than baked into the generated class, which is shared by all devices of a type.
"""

from abc import ABC, abstractmethod

from caproto.server import PVGroup
from dataclasses import dataclass
from typing import Callable, List
import warnings
import time
from ..effects.resolve import call_signal

DEFAULT_TIMESTEP = 0.1
"""Timestep used when the IOC runner does not specify one, in seconds."""


def _values_equal(a, b) -> bool:
    """Whether a readback already holds a value, avoiding a needless CA update.

    Waveform PVs compare element-wise, which is ambiguous as a truth value; such
    values are treated as changed and written.
    """
    try:
        return bool(a == b)
    except (TypeError, ValueError):
        return False


@dataclass
class PVPair:
    """A setpoint and the readback that follows it.

    `setpoint` and `readback` are the PV handles as defined in the device YAML,
    i.e. the attribute names on the generated IOC class. `dynamics` is the
    response model relating the two, called as ``dynamics(target, dt)``; with no
    response model the readback tracks its setpoint immediately.
    """

    setpoint: str
    readback: str
    dynamics: Callable | None = None

    def __call__(self, target, dt):
        if self.dynamics is None:
            return target
        return self.dynamics(target, dt)


@dataclass
class UpdateSignal:
    """A PV whose value is generated by a signal function."""

    handle: str
    signal: Callable


class SimulationPVBase:
    """A `PVGroup` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        if timestep <= 0:
            raise ValueError(f"timestep must be positive, got {timestep}")
        self.timestep = timestep
        self.pv_pairs = list(pv_pairs) if pv_pairs else []
        self.updates = list(updates) if updates else []
        self.elapsed = 0.0
        self._driving = False
        self._missing = set()

    def _channel(self, handle: str):
        """The channel for a PV handle, or None if this device does not have it.

        Devices of the same type do not all define the same PVs, so a pair or
        update naming an absent one is skipped rather than being an error. It is
        reported once, not on every tick.
        """
        channel = getattr(self, handle, None)
        if channel is None and handle not in self._missing:
            self._missing.add(handle)
            warnings.warn(
                f"{type(self).__name__} has no PV '{handle}'; not simulating it."
            )
        return channel


class PVASimulatedPVGroup(SimulationPVBase):
    """A `SimulationPVBase` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        super().__init__(
            timestep=timestep,
            pv_pairs=pv_pairs,
            updates=updates,
            *args,
            **kwargs,
        )


    def drive(self) -> None:
        """Advance the simulation forever, one `timestep` at a time.

        Every PV in a generated IOC calls this on startup, but only the first
        such call drives the group; the rest return immediately. Which PVs a
        given device exposes is not known when the class is generated, so this
        is the only way to guarantee the loop starts.
        """
        if self._driving or not (self.pv_pairs or self.updates):
            return
        self._driving = True
        while True:
            self.tick()
            time.sleep(self.timestep)

    def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        A PV can be driven by both a pair and an update signal -- a readback that
        lags its setpoint and is also noisy -- so the contributions are composed
        into one value and written once. Writing each separately would put both
        the clean and the noisy value on the wire, and a client monitoring the PV
        would see them alternate.
        """
        values = {}

        for pair in self.pv_pairs:
            setpoint = self._channel(pair.setpoint)
            readback = self._channel(pair.readback)
            if setpoint is None or readback is None:
                continue
            values[pair.readback] = (readback, pair(setpoint.current(), self.timestep))

        for update in self.updates:
            channel = self._channel(update.handle)
            if channel is None:
                continue
            # Start from this tick's value where a pair has already produced one,
            # so that noise is applied to the value the readback is moving to.
            _, current = values.get(update.handle, (None, channel.current()))
            values[update.handle] = (
                channel,
                call_signal(
                    update.signal,
                    t=self.elapsed,
                    value=current,
                    dt=self.timestep,
                ),
            )

        for channel, value in values.values():
            if not _values_equal(
                value[0] if isinstance(value, tuple) else value, channel.current()
            ):
                raw = channel.current().raw
                raw["value"] = value[0] if isinstance(value, tuple) else value
                channel.post(raw)

        self.elapsed += self.timestep


class CASimulatedPVGroup(PVGroup, SimulationPVBase):
    """A `PVGroup` that advances its simulated PVs on a fixed timestep.

    The timestep is chosen by whatever runs the IOCs and passed through at
    construction, so that every IOC in a simulated machine advances at the same
    rate.
    """

    def __init__(
        self,
        *args,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
        **kwargs,
    ):
        SimulationPVBase.__init__(
            self,
            timestep=timestep,
            pv_pairs=pv_pairs,
            updates=updates,
            *args,
            **kwargs,
        )
        PVGroup.__init__(self, *args, **kwargs)

    async def drive(self, async_lib) -> None:
        """Advance the simulation forever, one `timestep` at a time.

        Every PV in a generated IOC calls this on startup, but only the first
        such call drives the group; the rest return immediately. Which PVs a
        given device exposes is not known when the class is generated, so this
        is the only way to guarantee the loop starts.
        """
        if self._driving or not (self.pv_pairs or self.updates):
            return
        self._driving = True
        while True:
            await self.tick()
            await async_lib.library.sleep(self.timestep)

    async def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        A PV can be driven by both a pair and an update signal -- a readback that
        lags its setpoint and is also noisy -- so the contributions are composed
        into one value and written once. Writing each separately would put both
        the clean and the noisy value on the wire, and a client monitoring the PV
        would see them alternate.
        """
        values = {}

        for pair in self.pv_pairs:
            setpoint = self._channel(pair.setpoint)
            readback = self._channel(pair.readback)
            if setpoint is None or readback is None:
                continue
            values[pair.readback] = (readback, pair(setpoint.value, self.timestep))

        for update in self.updates:
            channel = self._channel(update.handle)
            if channel is None:
                continue
            # Start from this tick's value where a pair has already produced one,
            # so that noise is applied to the value the readback is moving to.
            _, current = values.get(update.handle, (None, channel.value))
            values[update.handle] = (
                channel,
                call_signal(
                    update.signal,
                    t=self.elapsed,
                    value=current,
                    dt=self.timestep,
                ),
            )

        for channel, value in values.values():
            if not _values_equal(value, channel.value):
                await channel.write(value)

        self.elapsed += self.timestep
