"""Runtime support for generated TANGO device servers.

Generated device classes derive from `TangoSimulatedDevice`, which serves the
variables of a device definition as TANGO attributes, and drives the same two
kinds of simulated behaviour as the EPICS IOCs do:

* setpoint/readback pairs (`PVPair`), where the readback follows its setpoint
  through a response model rather than instantly;
* update signals, where a variable's value is generated by a signal function.

Both are per-device, so they are held in a `SimulatedModel` built from the
device definition when the server starts, rather than baked into the generated
class, which is shared by all devices of a type. TANGO creates the devices
itself, so each one finds its model by name in `BINDINGS` as it initialises.
"""

import threading
import time
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Hashable, List

from tango import AttrWriteType, AutoTangoMonitor, DevState, EnsureOmniThread, Util
from tango.server import Device, attribute

from ..effects.resolve import call_signal
from .base_server import DEFAULT_TIMESTEP, PVPair, UpdateSignal, _values_equal


class SimulatedModel:
    """The values of one device definition's variables, keyed by handle.

    Values are read and written by clients through the TANGO devices serving
    them, and advanced on a timestep by the server, on different threads.
    """

    def __init__(
        self,
        name: str,
        timestep: float = DEFAULT_TIMESTEP,
        pv_pairs: List[PVPair] = None,
        updates: List[UpdateSignal] = None,
    ):
        if timestep <= 0:
            raise ValueError(f"timestep must be positive, got {timestep}")
        self.name = name
        self.timestep = timestep
        self.pv_pairs = list(pv_pairs) if pv_pairs else []
        self.updates = list(updates) if updates else []
        self.elapsed = 0.0
        self.values: Dict[str, Any] = {}
        self._listeners: Dict[str, Dict[Hashable, Callable[[Any], None]]] = {}
        self._missing = set()
        self._lock = threading.RLock()

    @property
    def simulated(self) -> bool:
        """Whether there is anything to advance on each timestep."""
        return bool(self.pv_pairs or self.updates)

    def seed(self, handle: str, value: Any) -> None:
        """Give a variable its initial value, unless it already has a value."""
        with self._lock:
            self.values.setdefault(handle, value)

    def read(self, handle: str) -> Any:
        with self._lock:
            return self.values[handle]

    def write(self, handle: str, value: Any) -> None:
        with self._lock:
            self.values[handle] = value
        self._notify(handle, value)

    def listen(self, handle: str, key: Hashable, listener: Callable) -> None:
        """Call `listener` with each new value of a variable.

        A listener replaces any registered earlier under the same `key`, so a
        device that is initialised again is not told of each change twice.
        """
        with self._lock:
            self._listeners.setdefault(handle, {})[key] = listener

    def _notify(self, handle: str, value: Any) -> None:
        with self._lock:
            listeners = list(self._listeners.get(handle, {}).values())
        for listener in listeners:
            listener(value)

    def _known(self, handle: str) -> bool:
        """Whether this device has a variable, reporting one it lacks once.

        Devices of the same type do not all define the same variables, so a
        pair or update naming an absent one is skipped rather than an error.
        """
        if handle in self.values:
            return True
        if handle not in self._missing:
            self._missing.add(handle)
            warnings.warn(f"{self.name} has no variable '{handle}'; not simulating it.")
        return False

    def tick(self) -> None:
        """Advance every pair and update signal by one timestep.

        A variable can be driven by both a pair and an update signal -- a
        readback that lags its setpoint and is also noisy -- so the
        contributions are composed into one value and written once, as they
        are for PVs.
        """
        with self._lock:
            values = {}

            for pair in self.pv_pairs:
                if not (self._known(pair.setpoint) and self._known(pair.readback)):
                    continue
                values[pair.readback] = pair(self.values[pair.setpoint], self.timestep)

            for update in self.updates:
                if not self._known(update.handle):
                    continue
                # Start from this tick's value where a pair has already produced
                # one, so that noise is applied to the value the readback is
                # moving to.
                current = values.get(update.handle, self.values[update.handle])
                values[update.handle] = call_signal(
                    update.signal,
                    t=self.elapsed,
                    value=current,
                    dt=self.timestep,
                )

            changed = {
                handle: value
                for handle, value in values.items()
                if not _values_equal(value, self.values[handle])
            }
            self.values.update(changed)
            self.elapsed += self.timestep

        for handle, value in changed.items():
            self._notify(handle, value)


@dataclass
class DeviceBinding:
    """The variables one TANGO device serves, and the model holding them.

    `handles` maps the name of each attribute to the handle of its variable.
    """

    model: SimulatedModel
    handles: Dict[str, str] = field(default_factory=dict)


BINDINGS: Dict[str, DeviceBinding] = {}
"""The binding of each device served by this process, by lower-cased name."""


def bind(device_name: str, binding: DeviceBinding) -> None:
    # TANGO does not tell device names apart by case
    BINDINGS[device_name.lower()] = binding


STOPPING = threading.Event()
"""Set as the server begins to shut down, after which nothing more is simulated."""


class TangoSimulatedDevice(Device):
    """A TANGO device serving the variables of a device definition.

    Generated classes declare the attributes that every device of their type
    has, along with `OPTIONAL_ATTRIBUTES`, which only some have and which are
    added to the devices that do. `INITIAL_VALUES` gives the value each
    attribute starts from.
    """

    INITIAL_VALUES: Dict[str, Any] = {}
    OPTIONAL_ATTRIBUTES: Dict[str, Dict[str, Any]] = {}

    def init_device(self):
        super().init_device()
        binding = BINDINGS.get(self.get_name().lower())
        if binding is None:
            warnings.warn(
                f"No device definition found for {self.get_name()}; "
                "serving its attributes without simulating them."
            )
            binding = DeviceBinding(model=SimulatedModel(self.get_name()))
        self._binding = binding
        self._unpushable = set()
        self._deleted = False
        for name in self._declared_attributes():
            self._serve(name)
        self.set_state(DevState.ON)

    def initialize_dynamic_attributes(self):
        for name, config in self.OPTIONAL_ATTRIBUTES.items():
            if name not in self._binding.handles:
                continue
            self.add_attribute(
                attribute(
                    name=name,
                    access=AttrWriteType.READ_WRITE,
                    fget=self._read_optional,
                    fset=self._write_optional,
                    **config,
                )
            )
            self._serve(name)
        for name in self._binding.handles:
            if name not in self.INITIAL_VALUES:
                warnings.warn(
                    f"{type(self).__name__} has no attribute '{name}' for "
                    f"{self.get_name()}; render the servers again to serve it."
                )

    def _declared_attributes(self) -> List[str]:
        """The attributes every device of this class has."""
        return [n for n in self.INITIAL_VALUES if n not in self.OPTIONAL_ATTRIBUTES]

    def _handle(self, name: str) -> str:
        # A device whose definition lacks an attribute its class declares still
        # has to serve it, and does so under the attribute's own name.
        return self._binding.handles.get(name, name)

    def _serve(self, name: str) -> None:
        """Start serving an attribute from the model, with change events."""
        model, handle = self._binding.model, self._handle(name)
        model.seed(handle, self.INITIAL_VALUES.get(name))
        # Clients expect the set point of a writable attribute to be readable
        # before anything has been written to it.
        try:
            written = self.get_device_attr().get_w_attr_by_name(name)
            written.set_write_value(model.read(handle))
        except Exception:
            pass
        # Changes are pushed by the model rather than detected by polling
        self.set_change_event(name, True, False)
        model.listen(
            handle, (self.get_name(), name), lambda value: self._push(name, value)
        )

    def delete_device(self):
        """Stop pushing events, as the server stops or the device is initialised again.

        The simulation runs on a thread of its own, and pushing an event for a
        device TANGO has begun to destroy brings the whole server down. Events
        are pushed holding the device's monitor, as everything TANGO does to a
        device is, so taking it here waits out a push that is under way. It is
        the only lock there is: a second would have to be taken before the
        monitor by the simulation, and after it by a client's write.
        """
        if Util.instance().is_svr_shutting_down():
            STOPPING.set()
        with AutoTangoMonitor(self):
            self._deleted = True
        super().delete_device()

    def _push(self, name: str, value: Any) -> None:
        if name in self._unpushable or self._deleted or STOPPING.is_set():
            return
        with AutoTangoMonitor(self):
            if self._deleted or STOPPING.is_set():
                return
            try:
                self.push_change_event(name, value)
            except Exception as exc:
                # Reported once: a signal producing a value its attribute cannot
                # hold would otherwise do so on every timestep.
                self._unpushable.add(name)
                warnings.warn(
                    f"Cannot push {self.get_name()}/{name} = {value!r}: {exc}"
                )

    def read_value(self, name: str) -> Any:
        return self._binding.model.read(self._handle(name))

    def write_value(self, name: str, value: Any) -> None:
        self._binding.model.write(self._handle(name), value)

    # Attributes added to a device are read and written through the attribute
    # itself, where those declared by a class are passed the value.

    def _read_optional(self, attr) -> Any:
        return self.read_value(attr.get_name())

    def _write_optional(self, attr) -> None:
        self.write_value(attr.get_name(), attr.get_write_value())


def drive(models: List[SimulatedModel], timestep: float = DEFAULT_TIMESTEP) -> None:
    """Advance `models`, one `timestep` at a time, until the server shuts down.

    Run on a thread of its own once the server's devices exist. Events pushed
    from a thread TANGO did not create must come from within `EnsureOmniThread`.
    """
    models = [model for model in models if model.simulated]
    if not models:
        return
    with EnsureOmniThread():
        while not STOPPING.is_set():
            for model in models:
                try:
                    model.tick()
                except Exception as exc:
                    # One faulty signal should not stop the rest of the machine
                    warnings.warn(f"Could not advance {model.name}: {exc}")
            time.sleep(timestep)
